### ISSUE TITLE
react-native ?

### ISSUE THREAD

**Issue by BerndWessels** [gaearon/react-hot-boilerplate#114]
What about `react-native`? It uses `react-transform` but that says its `deprecated` for this.

So will this work with `react-native` and if so then how?

**Comment by YasserKaddour** [comment]
React native already support hot reloading, here is the [blog post](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html) announcing it

**Comment by BerndWessels** [comment]
@YasserKaddour This is not the point. As the blog clearly says `react-native` uses `react-transform` for hot reloading. `react-transform` has a lot of issues that make `hot reloading` in `react-native` often useless.

What I am asking about is, if `react-native` will get `React Hot Loader 3` support.

I am following [this](https://github.com/gaearon/react-hot-boilerplate/pull/61) for a while and it seems to be coming for a long time - but I couldn't find any mentioning about `react-native`.

@gaearon you might be able to answer this?

**Comment by calesce** [comment]
There are no immediate plans to support React Native because it has its own packager and HMR implementation. It should be doable but we'd need someone willing (and have time :wink:) to work on it. Either way this request is more specific to React Hot Loader than to this boilerplate, so I'm going to close this.
