### ISSUE TITLE
webpack says nothing changed even when I added a line

### ISSUE THREAD

**Issue by neerajdotname** [gaearon/react-hot-boilerplate#20]
http://take.ms/0kfVz

I am using mac.

Is this because React should return only one element. If that is the case then ideally I should get an error in console. 

I see the error in terminal. Just wanted to know if it is possible to indicate someway that "hey something went wrong. Look at log in terminal.".

**Comment by neerajdotname** [comment]
If I use https://github.com/FrontendMasters/2015-02-13-React setup by @ryanflorence then I do get error message which is nice.

http://take.ms/7gCma

**Comment by gaearon** [comment]
This is because on `NoErrorsPlugin` in the config. You can remove it, but then HMR will break if you misspell an `import`. I'm not sure which is worse..

I'd like some kind of a middle solution here. Currently filed as https://github.com/webpack/webpack/issues/1105, so please track that issue if you're interested in the solution when/if it arrives.

**Comment by gaearon** [comment]
Remove `NoErrorsPlugin` and use React Hot Loader >= 1.3.0.

**Comment by neerajdotname** [comment]
Thanks.
