### ISSUE TITLE
Is this project on the deprecation path as well?

### ISSUE THREAD

**Issue by exiadbq** [gaearon/react-hot-boilerplate#44]
As react-hot-loader has the 'Deprecation Notice'.

**Comment by Andreyco** [comment]
It's primary dependency (react-hot-loader) is deprecated. I would not use it anymore. As suggested, use React Transform. Dan prepared boilerplate for that too https://github.com/gaearon/react-transform-boilerplate

**Comment by gaearon** [comment]
It’s a tricky situation because React Transform is also an unstable project and might change significantly later or get deprecated as well. For now I’d say they both have their own pros and cons.

**Comment by exiadbq** [comment]
So for new project development, which you would suggest to start with?

**Comment by gaearon** [comment]
If you use something like Redux to externalize your state I would suggest neither:  https://github.com/reactjs/redux/pull/1455.
Otherwise I can’t really suggest either because both have different problems. Try both and see what works better in your particular project. Hopefully I’ll have a better answer in a few months :-)
