### ISSUE TITLE
deploy to heroku

### ISSUE THREAD

**Issue by yonahforst** [gaearon/react-hot-boilerplate#79]
I'm new to webpack and babel. I'm trying to deploy this to heroku, but i think i need to change something first. Does anyone know of step by step instructions for deploying an app built on react-hot-boilerplate?

**Comment by lakhansamani** [comment]
@yonahforst you can go through following blog and repository for heroku deployment 
[Blog Link](http://ditrospecta.com/javascript/react/es6/webpack/heroku/2015/08/08/deploying-react-webpack-heroku.html)
[Github repo](https://github.com/wallacyyy/webpack-heroku)

**Comment by donpinkus** [comment]
I'm not sure hot-module replacement is working correctly with that repo.

If you clone it, build it (be sure to switch the build to the dev webpack), then start the server and try changing CSS, nothing happens.

**Comment by donpinkus** [comment]
Alright, just got this working. Here is what you need to do:

#### Step 1. Procfile
Heroku uses a Procfile to run commands to start your server. Add a file named `Procfile` to your project's root directory.  Put this line in it `web: node server.prod.js`.  Save it.  That tells Heroku to run the command `node server.prod.js`.  You don't have a server.prod.js file yet, so let's make that.

#### Step 2. server.prod.js
Create a `server.prod.js` file in your root directory.  You already have a server.js from this repo.  Your server.js file has a bunch of react hot reloading stuff in it, great for dev, bad for prod. 

In your `server.prod.js` file, paste this:

```
var express = require('express');
var app = express();

app.set('port', (process.env.PORT || 5000));

app.use(express.static(__dirname + '/public'));

// views is directory for all template files
app.get('/', function(request, response) {
  response.sendFile(__dirname + '/index.html');
});

app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});
```

It uses express to serve your index.html file.  

#### Step 3. Run `npm install express --save`
You use Express to serve your index file, so you need to install express and save it.  By the way, Heroku runs `npm install` when you push.

#### Step 4. Move `/dist/bundle.js` into `/public/bundle.js`
Make a folder in your root directory called "public". Copy your bundle.js file there.  

#### Step 5. Update your `webpack.config.js`
Change `publicPath: '/dist/` to `publicPath: `/public/`. Otherwise you'll get weird errors that modules can't be found when you try to use your `server.prod.js`.

#### Step 6. Update `index.html`
Have its bundle.js served from `/bundle.js`. It was being served from `/dist/bundle.js` which is going to 404 in production.  `/bundle.js` works since your express app set `/public/` as its static asset folder, so any route that doesn't match something is going to be checked in `public/` for a match. 

#### Step 7. deploy
Push your app to heroku. 


Note: I'm still editing this to work well with development, but at the very least this will get you deployed to prod without totally f*ing your setup. You're just adding a procfile, a server you use for heroku, and placing your files in a place where that server will get them.

**Comment by calesce** [comment]
@donpinkus want to make a PR and add something like `Deploy_to_Heroku.md`?

**Comment by calesce** [comment]
I think [create-react-app](https://github.com/facebookincubator/create-react-app) better serves this purpose, they have extensive guides on building/deploying.
